[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "discord-boost-checker"
version = "0.3.0"
authors = [
  { name = "mOon", email = "mohamed835misgxyd@gmail.com" }
]
description = "Internal utility package."
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.8"
keywords = ["discord", "discord-api", "async"]

dependencies = [
    "requests>=2.28.0",
    "aiohttp>=3.8.0"
]

[project.urls]
"Homepage" = "https://github.com/69xr/discord-boost-checker"
"Bug Tracker" = "https://github.com/69xr/discord-boost-checker/issues"

[project.scripts]
discord-boost = "discord_boost_checker.cli:main"
